# Generated by Django 4.0 on 2024-01-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dynamic_fields',
            field=models.JSONField(default=dict),
        ),
    ]
